feature/update sending device descriptions notes
DKE-Data/agrirouter-interface-documentation pull request #100
Opened 2020-11-05 15:59 UTC by saschadoemer

2020-11-06 07:23 UTC, Frank-Wiebeler requested changes
Good job so far, I just request some minor grammar changes

2020-11-06 07:23 UTC, Frank-Wiebeler commented on docs/commands/endpoint.adoc
> +Please note that the device description has to be sent every time before the maschine starts sending live telemetry data to ensure, that each other endpoint is able to update their formerly received
machine

2020-11-06 07:23 UTC, Frank-Wiebeler commented on docs/commands/endpoint.adoc
> +Please note that the device description has to be sent every time before the maschine starts sending live telemetry data to ensure, that each other endpoint is able to update their formerly received
Please note that the device description has to be sent every time before the machine starts sending live telemetry data to ensure, that every other endpoint is able to update their formerly received device descriptions and new endpoints get the latest updates as well.

2020-11-06 07:23 UTC, Frank-Wiebeler commented on docs/communication.adoc
> +====
Please note that the device description has to be sent every time before the machine starts sending live telemetry data to ensure, that every other endpoint is able to update their formerly received device descriptions and new endpoints get the latest updates as well.

2020-11-06 07:23 UTC, Frank-Wiebeler commented on docs/messaging-workflow.adoc
> +Please note that the device description has to be sent every time before the maschine starts sending live telemetry data to ensure, that each other endpoint is able to update their formerly received
Please note that the device description has to be sent every time before the machine starts sending live telemetry data to ensure, that every other endpoint is able to update their formerly received device descriptions and new endpoints get the latest updates as well.

2020-11-06 07:23 UTC, Frank-Wiebeler commented on docs/tmt/efdi.adoc
> +Please note that the device description has to be sent every time before the maschine starts sending live telemetry data to ensure, that each other endpoint is able to update their formerly received
Please note that the device description has to be sent every time before the machine starts sending live telemetry data to ensure, that every other endpoint is able to update their formerly received device descriptions and new endpoints get the latest updates as well.

2020-11-06 07:23 UTC, Frank-Wiebeler commented on docs/commands/endpoint.adoc
> +The teamset describes a list of devices attached to the communication unit. The most common devices are agricultural machines connected to the CU as ISO11783-10 task controllers. For more information
The teamset describes a list of devices attached to the communication unit. The most common devices are agricultural machines connected to the CU via an ISO11783-10 task controller client. For more information on ISO11783-10, please refer to https://aef-online.org

2020-11-24 11:28 UTC, Frank-Wiebeler requested changes
Some minor grammar topics; please adjust the text at the other added paragraphs as well

2020-11-24 11:28 UTC, Frank-Wiebeler commented on docs/commands/endpoint.adoc
> +Please note that the device description has to send every time before the machine starts sending live telemetry data to ensure, that each other endpoint is able to update their formerly received devi
...has to be sent...

2020-11-24 11:28 UTC, Frank-Wiebeler commented on docs/commands/endpoint.adoc
> +Please note that the device description has to send every time before the machine starts sending live telemetry data to ensure, that each other endpoint is able to update their formerly received devi
...formerly received device descriptions ... (no s)

2020-11-24 11:28 UTC, Frank-Wiebeler commented on docs/commands/endpoint.adoc
> +Please note that the device description has to send every time before the machine starts sending live telemetry data to ensure, that each other endpoint is able to update their formerly received devi
as mentioned, for new endpoints that should not be an issue, so we can remove "and new endpoints get the latest updates as well"

2021-05-27 08:25 UTC, oliverrahner commented
Has been manually integrated into #113 in https://github.com/DKE-Data/agrirouter-interface-documentation/pull/113/commits/81888f9675bbdbf9e932c307bcf258352f98feaf

2021-05-27 08:25 UTC, closed without merging