Documentation 2.0
DKE-Data/agrirouter-interface-documentation pull request #198
Opened 2024-09-25 12:28 UTC by Frank-Wiebeler

Update Documentation to fit the new agrirouter implementation

2024-09-25 12:51 UTC, oliverrahner requested changes
All file

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/assets/images/graphs/image15.SVG
All file names should be lowercase

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/assets/images/graphs/image18.SVG
One arrow remaining in old color
"No" branch should be green, "Yes" branch should be red

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/commands/endpoint.adoc
> +## include::partial$device-description-has-to-be-sent-every-time.adoc[]
Add back

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/commands/endpoint.adoc
> +#For the certification it is required to send the device description message multiple times. Therefore, it must either be sent on manual request (request must be performable by the test processing pe
Add back

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/glossary.adoc
> -The user-defined agrirouter routings define which parameters of which machine may go to which recipient. In addition, recipients can subscribe for certain parameters they want to get (sender-independ
Re-add that first sentence, but put "... parameters from which (V)CU may go..."

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/glossary.adoc
> +## todo
Remove

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/ids-and-definitions.adoc
> +Switching GatewayID MQTT<-> HTTP works, but it may only be used for
missing space (" <->")

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/integration/authorization.adoc
> +play when an authorize request does not provide a redirect URL (or provides an invalid one).
"Please note that this behavior is DEPRECATED and we will require a VALID redirect URL to be provided to an authorize request in the future."
--> Please also note this in the "Parameters" section

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/integration/onboarding.adoc
> +The registration code for a new CU can be created by the end user clicking "Onboard Telemetry Unit" in agrirouter's control center. He gets a 10-digit code consisting of letters and numbers. A CU nee
Button should be called "+ Connection"

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/limitations.adoc
>  | Machines | 300
also needs to be removed

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/limitations.adoc
>  | Groups | 20
also needs to be removed

2024-09-25 12:51 UTC, oliverrahner commented on modules/ROOT/pages/messaging-workflow.adoc
>  With except to the EFDI telemetry messages (DeviceDescription and timelogs), agrirouter doesn’t analyse the messages inside the agrirouter command. It just checks the message type and the addressing
With the exception of...

2024-10-24 13:14 UTC, Frank-Wiebeler commented
Closed as the merge was done via a different branch to ensure the pipelines run

2024-11-04 21:32 UTC, Frank-Wiebeler commented
Closed as it's not needed anymore

2024-11-04 21:32 UTC, closed without merging